spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/easycodepro?currentSchema=sb_jpa
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
server:
  port: 8181